// This file is regenerated by `pnpm abi:sync` after `hardhat compile`.
// Until contracts compile for the first time, the ABIs below are empty placeholders.

export const RealityProofAbi = [] as const;
export const DeviceRegistryAbi = [] as const;

export type RealityProofAbiType = typeof RealityProofAbi;
export type DeviceRegistryAbiType = typeof DeviceRegistryAbi;
