/**
 * Pulls the compiled ABI from `contracts/artifacts` and emits a typed TS module
 * at `packages/contracts-abi/src/index.ts`.
 *
 * Run: `pnpm abi:sync` (after `pnpm --filter @proof-of-reality/contracts compile`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../../..");
const ARTIFACTS = join(ROOT, "contracts", "artifacts", "contracts");
const OUT = join(import.meta.dirname, "..", "src", "index.ts");

const CONTRACTS = ["RealityProof", "DeviceRegistry"] as const;

function readAbi(name: string): unknown[] {
  const path = join(ARTIFACTS, `${name}.sol`, `${name}.json`);
  const json = JSON.parse(readFileSync(path, "utf8")) as { abi: unknown[] };
  return json.abi;
}

function emit() {
  const lines: string[] = [
    "// AUTO-GENERATED by packages/contracts-abi/scripts/sync.ts",
    "// Do not edit by hand. Run `pnpm abi:sync` to regenerate.",
    "",
  ];

  for (const name of CONTRACTS) {
    let abi: unknown[];
    try {
      abi = readAbi(name);
    } catch (e) {
      console.warn(`[abi-sync] ${name} not found — skipping (run hardhat compile first)`);
      abi = [];
    }
    lines.push(`export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
    lines.push(`export type ${name}AbiType = typeof ${name}Abi;`);
    lines.push("");
  }

  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`[abi-sync] wrote ${OUT}`);
}

emit();
